const blogPosts = [
    {index: 1,
    date: "July 23, 2022",
    title: "Blog One",
    description: "I'm excited to start a new learning journey as a Scrimba Bootcamp student! After several months of learning in the Frontend Developer Career Path.",
        },
    {index: 2,
        date: "July 23, 2022",
        title: "Blog Two",
        description: "I'm excited to start a new learning journey as a Scrimba Bootcamp student! After several months of learning in the Frontend Developer Career Path.",
        },
    {index: 3,
        date: "July 23, 2022",
        title: "Blog Three",
        description: "I'm excited to start a new learning journey as a Scrimba Bootcamp student! After several months of learning in the Frontend Developer Career Path.",
        },
    {index: 4,
        date: "July 23, 2022",
        title: "Blog Four",
        description: "I'm excited to start a new learning journey as a Scrimba Bootcamp student! After several months of learning in the Frontend Developer Career Path.",
        },
    {index: 5,
        date: "July 23, 2022",
        title: "Blog Five",
        description: "I'm excited to start a new learning journey as a Scrimba Bootcamp student! After several months of learning in the Frontend Developer Career Path.",
        },
    {index: 6,
        date: "July 23, 2022",
        title: "Blog Six",
        description: "I'm excited to start a new learning journey as a Scrimba Bootcamp student! After several months of learning in the Frontend Developer Career Path.",
        }
]

export default blogPosts